version: '3'
services:
    
  redis_server:
    build:
      context: ./redis_server/
    container_name: xpec_redis
    depends_on:
      - web_server
      - cache_server
      - database_server
    volumes:
      - ./redis_server/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    links:
      - web_server
      - database_server

    ports:
      - "6379:6379"

  cache_server:
    build:
      context: ./cache_server/
    container_name: xpec_varnish
    depends_on:
      - web_server
      - database_server
    volumes:
      - ./cache_server/default.vcl:/etc/varnish/default.vcl
      - ./cache_server/varnish:/etc/default/varnish
      - ./cache_server/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    ports:
      - "80:80"
      - "443:443"
    links:
      - web_server
      - database_server

  web_server:
    build:
      context: ./web_server/
    container_name: xpec_apache2
    volumes:
      - ./proyectos:/var/www/html  
      - ./web_server/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
      - ./web_server/virtualhosts/:/etc/apache2/sites-available/
    ports:
      - "8080:8080"
    links:
      - database_server
    
  database_server:
    build:
      context: ./database_server/
      args:
        - mysql_password=12345
        - mysql_database=magento233
    container_name: xpec_mysql
    volumes: 
      - ./database_server/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
      - ./database_server/mysql.sh:/etc/mysql.sh
      - ./database_server/db_import/:/var/db_import
    ports:
      - "3306:3306"

  elasticsearch_server:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
    container_name: xpec_elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - ./elasticsearch_server:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
